[package]
name = "masm-instructions"
version = "0.1.0"
edition = "2021"

[dependencies]
miden-assembly-syntax = { version = "0.20", default-features = true }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
